"""Initial schema

Revision ID: 8f8db0e0dced
Revises: 
Create Date: 2026-07-17 17:59:07.077429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8db0e0dced'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('utm_zone', sa.String(), nullable=True),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('import_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trench',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('trench_id', sa.String(), nullable=False),
    sa.Column('easting', sa.Float(), nullable=True),
    sa.Column('northing', sa.Float(), nullable=True),
    sa.Column('grade_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trench_project_id'), 'trench', ['project_id'], unique=False)
    op.create_table('wireframe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('solid_type', sa.String(), nullable=False),
    sa.Column('file_ref', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireframe_project_id'), 'wireframe', ['project_id'], unique=False)
    op.create_table('collar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('hole_id', sa.String(), nullable=False),
    sa.Column('easting', sa.Float(), nullable=False),
    sa.Column('northing', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('utm_zone', sa.String(), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['collar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collar_project_hole', 'collar', ['project_id', 'hole_id'], unique=False)
    op.create_index(op.f('ix_collar_project_id'), 'collar', ['project_id'], unique=False)
    op.create_table('assay_interval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collar_id', sa.UUID(), nullable=False),
    sa.Column('from_depth', sa.Float(), nullable=False),
    sa.Column('to_depth', sa.Float(), nullable=False),
    sa.Column('grade_value', sa.Numeric(), nullable=False),
    sa.Column('grade_unit', sa.String(), nullable=False),
    sa.Column('below_detection_limit', sa.Boolean(), nullable=False),
    sa.Column('qaqc_flag', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['collar_id'], ['collar.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['assay_interval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assay_collar_depths', 'assay_interval', ['collar_id', 'from_depth', 'to_depth'], unique=False)
    op.create_index(op.f('ix_assay_interval_collar_id'), 'assay_interval', ['collar_id'], unique=False)
    op.create_table('lithology_interval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collar_id', sa.UUID(), nullable=False),
    sa.Column('from_depth', sa.Float(), nullable=False),
    sa.Column('to_depth', sa.Float(), nullable=False),
    sa.Column('lith_code', sa.String(), nullable=False),
    sa.Column('rqd_percent', sa.Integer(), nullable=True),
    sa.Column('core_recovery_percent', sa.Integer(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['collar_id'], ['collar.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['lithology_interval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lith_collar_depths', 'lithology_interval', ['collar_id', 'from_depth', 'to_depth'], unique=False)
    op.create_index(op.f('ix_lithology_interval_collar_id'), 'lithology_interval', ['collar_id'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collar_id', sa.UUID(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('dip', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=False),
    sa.Column('desurvey_method', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collar_id'], ['collar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_collar_id'), 'survey', ['collar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_collar_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_lithology_interval_collar_id'), table_name='lithology_interval')
    op.drop_index('idx_lith_collar_depths', table_name='lithology_interval')
    op.drop_table('lithology_interval')
    op.drop_index(op.f('ix_assay_interval_collar_id'), table_name='assay_interval')
    op.drop_index('idx_assay_collar_depths', table_name='assay_interval')
    op.drop_table('assay_interval')
    op.drop_index(op.f('ix_collar_project_id'), table_name='collar')
    op.drop_index('idx_collar_project_hole', table_name='collar')
    op.drop_table('collar')
    op.drop_index(op.f('ix_wireframe_project_id'), table_name='wireframe')
    op.drop_table('wireframe')
    op.drop_index(op.f('ix_trench_project_id'), table_name='trench')
    op.drop_table('trench')
    op.drop_table('import_batch')
    op.drop_table('user_account')
    op.drop_table('project')
    # ### end Alembic commands ###
