"""add structural and qaqc tables

Revision ID: bc78a0b106d0
Revises: d1a2b3c4e5f6
Create Date: 2026-07-18 02:49:22.329611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc78a0b106d0'
down_revision: Union[str, Sequence[str], None] = 'd1a2b3c4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qaqc_standard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('standard_name', sa.String(), nullable=False),
    sa.Column('expected_grade_min', sa.Float(), nullable=False),
    sa.Column('expected_grade_max', sa.Float(), nullable=False),
    sa.Column('grade_unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qaqc_standard_project_id'), 'qaqc_standard', ['project_id'], unique=False)
    op.create_table('structural_reading',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reading_type', sa.String(), nullable=False),
    sa.Column('easting', sa.Float(), nullable=False),
    sa.Column('northing', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('dip', sa.Float(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['structural_reading.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structural_reading_project_id'), 'structural_reading', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structural_reading_project_id'), table_name='structural_reading')
    op.drop_table('structural_reading')
    op.drop_index(op.f('ix_qaqc_standard_project_id'), table_name='qaqc_standard')
    op.drop_table('qaqc_standard')
    # ### end Alembic commands ###
